background {
    monitor =
    path = /usr/share/sddm/themes/sddm-astronaut-theme/Backgrounds/login.jpg 
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(205edf)
    inner_color = rgb(f1f3f0)
    font_color = rgb(000000)
    placeholder_text = Password
    rounding = 3
    font_size = 12
    fail_color = rgb(f38ba8)
    fail_text = Wrong Password

 }
