color=1e1e2eff
ring-color=602080ff
key-hl-color=602080ff
line-color=00000000
inside-color=1e1e2eff
separator-color=00000000
text-color=cdd6f4ff
ring-ver-color=602080ff
inside-ver-color=1e1e2eff
ring-wrong-color=f38ba8ff
inside-wrong-color=1e1e2eff
